name = "Automata"
defaultTargets = ["Automata"]

[[lean_lib]]
name = "Automata"

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[require]]
name = "extra"
git = "https://github.com/fgdorais/extra4"
rev = "main"
